import ColorProvider from "@/context/ColorProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import { ItemsProvider } from "@/context/ItemsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ColorProvider>
        <ItemsProvider>
          <body className={inter.className}>{children}</body>
        </ItemsProvider>
      </ColorProvider>
    </html>
  );
}
