import Main from '@/components/dashboard/Main'
export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <Main />
    )
}

export default page